Repository campa-consortium/pals, pull requests merged in 2025-07, with the labels that each got.

#59 First Example: FODO Cell
  examples/fodo.pals.yaml
Labels: documentation

#71 Sphinx: Copybutton
  source/conf.py
Labels: standard document, enhancement

#64 Patch parameters and other changes.
  README.md
  source/coordinates.md
  source/element-kinds.md
  source/element-parameters.md
  source/figures/patch.svg
  source/how-to-write-docs.md
  source/introduction.md
  source/libraries.md
  source/parameters/ackicker.md
  source/parameters/beambeam.md
  source/parameters/bend.md
  source/parameters/bodyshift.md
  source/parameters/electricmultipole.md
  source/parameters/floor.md
  source/parameters/floorshift.md
  source/parameters/magneticmultipole.md
  source/parameters/meta.md
  source/parameters/patch.md
  source/parameters/reference.md
  source/parameters/referencechange.md
  source/parameters/rf.md
  source/parameters/solenoid.md
Labels: standard document, elements
