Repository campa-consortium/pals, pull requests merged in 2025-06, with the labels that each got.

#60 `conda.y(a)ml`
  .readthedocs.yaml
  conda.yaml
  source/how-to-write-docs.md
Labels: documentation

#62 Sphinx LaTeX: Support SVG
  conda.yaml
  source/conf.py
Labels: bug

#61 File Formats & Libraries
  source/fileformats.md
  source/index.md
  source/libraries.md
  source/simulations.md
Labels: documentation

#65 Fix Read the Docs builds
  .github/workflows/deploy.yml
  source/parameters/bend.md
Labels: bug, documentation

#63 Fix LaTeX Issues
  source/parameters/bend.md
  source/parameters/referencechange.md
Labels: help wanted
